### ISSUE TITLE
Support multiparameter attributes

### ISSUE THREAD

**Issue by rzane** [nicolasblanco/rails_param#11]
It would be nice if this library supported the multiparameter attributes submitted by the following:

+ `date_select`
+ `time_select`
+ `datetime_select`

These inputs submit values that work nicely for models, but if you're trying to access that value in your controller, it's always really ugly because you have to do something like this:

```ruby
Date.civil(params[:report]["start_date(1i)"].to_i,
           params[:report]["start_date(2i)"].to_i,
           params[:report]["start_date(3i)"].to_i)
```

**Comment by nicolasblanco** [comment]
Hi,

This library was never intended to support all the features of ActiveModel inside controllers.
Its main use is to validate a very few number of parameter sent without namespacing and without a form.

If you want to validate parameters sent via a form you have to use an ActiveModel form class.

**Comment by rzane** [comment]
Okay, thanks anyway!

**Comment by nicolasblanco** [comment]
In the case you don't know ActiveModel::Model, I've added in the README a link to a page explaining it. Thanks.

**Comment by rzane** [comment]
Multiparameter attribute handling is part of ActiveRecord::AttributeAssignment, not ActiveModel. Take a look at: https://github.com/rails/rails/pull/8189.

I think it would be common to want to accept a date in a controller, rather than model. I also don't think this would violate the fat controller policy. Sometimes, I just want to accept a single date field.
