### ISSUE TITLE
Empty string as default

### ISSUE THREAD

**Issue by alolis** [nicolasblanco/rails_param#12]
The following:

`param! :q, String, default: ""`

does not seems to work. No `q` key is set in my `params` if I have an empty string as a default. It works if I use a non empty string

**Comment by nicolasblanco** [comment]
@alolis : have you succeeded in writing a failing test?

**Comment by alolis** [comment]
I haven't tried writing a test, I am just reporting it.

**Comment by nicolasblanco** [comment]
No problem, if you have some time do it otherwise I will try to write one in my free time.

**Comment by piya23300** [comment]
I think my issue #18 is fixed. It will work for this case.

**Comment by iMacTia** [comment]
Indeed this should have been fixed in #17
