### ISSUE TITLE
Friendly url issue

### ISSUE THREAD

**Issue by antulik** [nicolasblanco/rails_param#15]
we have friendly ids like '41-hello', there is no way to convert and validate with rails_param.

**Comment by antulik** [comment]
my work around is

```ruby
param! :program_id, String, required: true, transform: :to_i
```

but would be nice to have a built in solution for such common usecase

**Comment by iMacTia** [comment]
I'm not really sure what you were trying to achieve this, maybe you want to use `format`?
Check out the last example to see it's usage: https://github.com/nicolasblanco/rails_param#example

Closing for now as really hold, but please feel free to reopen if needed
