### ISSUE TITLE
Ignore blank values

### ISSUE THREAD

**Issue by antulik** [nicolasblanco/rails_param#16]
I'd like to have an option something like `ignore_blank: true`

so with example

``` ruby
params = {
  period: ''
}
param! :period, String, in: %w(day week month), default: 'day', ignore_blank: true
```

the `in` validation won't be triggered

**Comment by iMacTia** [comment]
This can easily be achieved with:

```ruby
param! :period, String, in: %w(day week month), default: 'day', unless params[:period].blank?
```

We don't want the gem to grow indefinitely adding features for every possible edge-case.
In this case, it's also very easy to get around it, so please use the proposed fix.
If for whatever reason this doesn't work, please feel free to reopen.
