### ISSUE TITLE
Nested param

### ISSUE THREAD

**Issue by alolis** [nicolasblanco/rails_param#4]
Hello,

I have a `form_for`, named `:my_form` inside a view and all my parameters for that form come in my controller like this:

`params[:my_form][:my_param]`

which means that it's not possible for me to do a `param :my_param` declaration. The only workaround is to use `form_tag` instead of `form_for` inside my view.

Thank you for your time

**Comment by alolis** [comment]
Never mind, just saw this https://github.com/nicolasblanco/rails_param/issues/3

**Comment by nicolasblanco** [comment]
I've just accepted a pull request that allows nested params! See the README

**Comment by alolis** [comment]
Ah nice, cheers!
