### ISSUE TITLE
Raising custom error messages

### ISSUE THREAD

**Issue by akartik80** [nicolasblanco/rails_param#47]
## Basic Info

* rails_param Version: 0.10.1
* Ruby Version: 2.5.1
* Rails Version: 5.2.0

## Issue description
Big fan of this gem, reduces a lot of dev effort in validating parameters. One small thing I found out though: custom messages with message option does not work, it still throws up parameter XXX is required

## Steps to reproduce
Taking the example in readme, if you do
`param! :q, String, required: true, message: "Query not specified"`

it still throws up: `Parameter q is required` instead of `Query not specified`

**Comment by iMacTia** [comment]
Hi @akartik80, thanks for using `rails_param` and for raising this!
Indeed that functionality was added in the 0.10.1 release so I'll raise this as a bug and look into it as soon as possible.

**Comment by iMacTia** [comment]
@akartik80 Please see my update comment above

**Comment by akartik80** [comment]
I see it fixed in https://github.com/nicolasblanco/rails_param/pull/42/files with 0.10.2
