### ISSUE TITLE
Hash Conversion Issue

### ISSUE THREAD

**Issue by danrpts** [nicolasblanco/rails_param#49]
## Basic Info

* rails_param Version: 0.10.2
* Ruby Version: 2.4.2
* Rails Version: 4.2.11.1

## Issue description
When an Integer, Float, Bool or another type without a split method is supplied when expecting a Hash an exception is thrown that is not caught by the ArgumentError rescue. For example, when passing a `1` instead of `{}` raises error:
```
undefined method `split' for 1:Integer
```

## Steps to reproduce
Setup the params:
```
param! :person, Hash do |p|
 p.param! :name, String
end
```

Then send payload:
```
{
  "person": 1
}
```

**Comment by iMacTia** [comment]
Thank you @danrpts for raising this complete with steps to reproduce and apologies for the slow reply.
I'll investigate as I agree with you the correct behaviour in this case would be to raise an `InvalidParameterError`

**Comment by danrpts** [comment]
@iMacTia great! Thanks for the patch
