### ISSUE TITLE
support nested params

### ISSUE THREAD

**Issue by odigity** [nicolasblanco/rails_param#5]
I know that nested params tends to usually happen when dealing with model-back resources, and that in those cases you're supposed to rely on your model validations.

However, that pattern doesn't work for me.  I can't just stick the data into my model and call .validate!, because I'm validating far more than basic data types and values.  I'm also validating complex inter-model relationships with the help of a Service object, and I need to type-and-value sanitize the params in the Controller before passing them to the Service object.

rails_param looks awesome, and would be of great help with this, except it only takes param names as a symbol, and therefore there's no way to handle nested params such as params[:user][:name].

**Comment by stantoncbradley** [comment]
We had the same issue.  Check the docs now, rails_param takes a block for nested attributes and also handles arrays.

**Comment by odigity** [comment]
That is fantastic -- thanks!

PS-It annoys me that this gem is more popular, especially since it affects my decision of whether to use it.  I think it's because it goes against the Rails way passing the data straight to a model build and letting the validations deal with them.  But that way is so limited to the most basic, text-book case...

**Comment by nicolasblanco** [comment]
@odigity : even if I've accepted a PR to support nested params, I still does not understand why you don't use ActiveModel::Model virtual classes to validate nested params. This feature is already included in Rails and support all the classical Rails validations out of the box.

I still think that if you need to validate nested params inside a controller you are already too far from the first goal of this gem and may break the "thin controller" rule.

**Comment by odigity** [comment]
@nicolasblanco -- Why do you assume that all controller params always map to the concept of a model?  And why do you assume ActiveModel validators is always the right way to validate input?

**Comment by iMacTia** [comment]
Closing this as main question as been addressed 👍 !
