### ISSUE TITLE
"in" doesn't throw an error when unexpected value given

### ISSUE THREAD

**Issue by fatihky** [nicolasblanco/rails_param#56]
## Basic Info

* rails_param Version: `0.11.0`
* Ruby Version: `ruby 2.6.3p62`
* Rails Version: `Rails 6.0.0.rc2`

## Issue description
`param!` function doesn't throw a `RailsParam::Param::InvalidParameterError` if parameter value is not in the allowed values which specified with `in` argument.

## Steps to reproduce
1. Create a rails controller.
2. Add this line to the controller method `param! :order, String, %w(asc desc), default: 'asc'`
3. Call the controller method with `?order=neither_asc_nor_desc`

**Comment by iMacTia** [comment]
@fatihky thanks for opening this. Unfortunately I've tried adding Rails 6.0.0 to the Travis matrix and added a test to reproduce your issue (you can see the test [here](https://github.com/nicolasblanco/rails_param/pull/57/files#diff-ec8798ff52a15f01350918e1a9b9731bR629), but with no success (all tests are passing).

Could you double-check that the parameter is correctly passed to the controller and the value you read is `neither_asc_nor_desc`? You could also try temporarily making the parameter `required` to ensure the controller is receiving it correctly.

**Comment by fatihky** [comment]
Hi, I had written a concern that have `validate!` method. Now I noticed that it overrides your `validate!` method. It seems the problem isn't with your library.
Thank you for your response and great gem.
