### ISSUE TITLE
when nil in required param `transform` fails

### ISSUE THREAD

**Issue by shaul75** [nicolasblanco/rails_param#59]
## Basic Info

* rails_param Version: 0.11.0
* Ruby Version: 2.6
* Rails Version: 4.2.10

The following is a required param, if the param is missing a `Parameter type is required (400)` exception should be thrown. However, the transform executes before the required validation and to_sym throws `undefined method to_sym for nil:NilClass`.

`param! :type, String, required: true, in: %i[quarterly annual], transform: :to_sym
`

**Comment by iMacTia** [comment]
@shaul75 that is a good point actually!

It seems like [transformation](https://github.com/nicolasblanco/rails_param/blob/master/lib/rails_param/param.rb#L35) is applied before [validation](https://github.com/nicolasblanco/rails_param/blob/master/lib/rails_param/param.rb#L40), which makes sense, but the [check on parameter presence](https://github.com/nicolasblanco/rails_param/blob/master/lib/rails_param/param.rb#L136) currently happens as part of validation.

We should move that check outside and run it before transformation happens.

**Comment by johnschult** [comment]
Still a bug, no takers on this huh?

**Comment by iMacTia** [comment]
No takers yet unfortunately @johnschult  😞

**Comment by kmathesw** [comment]
@iMacTia, Do you have some time to review this PR #60
