### ISSUE TITLE
Unable to load application: NameError: uninitialized constant RailsParam::Param

### ISSUE THREAD

**Issue by RobertChanphakeo** [nicolasblanco/rails_param#63]
## Basic Info
* rails_param Version: latest (https://github.com/nicolasblanco/rails_param/commit/7ef301862051f11a5760f3ae4ae7f11968ee6954)
* Ruby Version: ruby 2.6.5-p114
* Rails Version: 4.2.11.1

## Issue description
Latest code refactor from 3 days ago https://github.com/nicolasblanco/rails_param/commit/7ef301862051f11a5760f3ae4ae7f11968ee6954

Raised an error "Unable to load application: NameError: uninitialized constant RailsParam::Param" https://pastebin.pl/view/5f75a8ea

## Steps to reproduce
Build rails_para using the latest code in the master branch.

## Workaround
Build rails_para using commit: 8235f1b074588bed1d787bca6e5d7ce12c42b5ec v0.11.1 or lower
https://github.com/nicolasblanco/rails_param/commit/8235f1b074588bed1d787bca6e5d7ce12c42b5ec

**Comment by iMacTia** [comment]
@RobertChanphakeo I can see that error is coming from a `rescue_concern` which sounds like a file where you have all the `rescue_from` declarations.
If that's the case, you're most probably rescuing `RailsParam::Param::InvalidParameterError`.
Good news is that you should be able to use `master` by simply changing that to rescuing `RailsParam::InvalidParameterError` 👍 

Please give it a try and let me know if you face any other issues! This is a great test case for the refactoring 😃

**Comment by RobertChanphakeo** [comment]
> @RobertChanphakeo I can see that error is coming from a `rescue_concern` which sounds like a file where you have all the `rescue_from` declarations.
> If that's the case, you're most probably rescuing `RailsParam::Param::InvalidParameterError`.
> Good news is that you should be able to use `master` by simply changing that to rescuing `RailsParam::InvalidParameterError` 👍
> 
> Please give it a try and let me know if you face any other issues! This is a great test case for the refactoring 😃

@iMacTia genius! it worked!

**Comment by iMacTia** [comment]
Glad it worked 🎉 !
