### ISSUE TITLE
[CI] Review Rails versions matrix

### ISSUE THREAD

**Issue by iMacTia** [nicolasblanco/rails_param#65]
## Issue description

We currently test against different Ruby/Rails version combinations.
Some of these are EOL, as you can see [here for Ruby](https://endoflife.date/ruby) and [here for Rails](https://endoflife.date/rails).

Releasing v1.0 is a great opportunity to drop support for these.
Nothing forces us to support EOL'ed versions, although users with older applications will definitely appreciate the gesture, but if the codebase can potentially be simplified (with positive effects on the maintenance burden), then we should probably consider to drop at least a few of them.

After the release (or at the same time?) we should also consider adding 3.0 to the CI matrix and see if `rails_param` works with that as well.

**Comment by ifellinaholeonce** [comment]
@iMacTia do you know much about:
```
platforms :rbx do
  gem 'racc'
  gem 'rubysl'
end
```
in the Gemfile? I failed to bundle locally using Ruby 3.0.1. However, yanking out these lines allowed me to bundle and have all the specs pass. The error when trying to bundle was:
```
    rails_param was resolved to 0.11.1, which depends on
      rails (>= 3.2.0) was resolved to 6.1.3.2, which depends on
        bundler (>= 1.15.0) was resolved to 2.2.15, which depends on
          Ruby (>= 2.3.0)

    rubysl was resolved to 1.1.0, which depends on
      rubysl-irb (~> 1.0) was resolved to 1.0.2, which depends on
        Ruby (~> 1.8.7)
```

**Comment by iMacTia** [comment]
That's strange... `rbx` stays for [Rubinius](https://github.com/rubinius/rubinius), so if you're bundling under MRI 3.0.1 it shouldn't try to install those dependencies 🤔

**Comment by ifellinaholeonce** [comment]
Yeah that's what I thought too. I'll keep digging a bit, not sure what's up

**Comment by ifellinaholeonce** [comment]
I was eventually able to get this to work locally by running `bundle --local` which I found from this discussion https://github.com/rubygems/bundler/issues/2774

All of that is from quite a while ago tho, so not sure why it's coming up now.

I tried adding Ruby 3 https://github.com/nicolasblanco/rails_param/pull/71 but it is failing in the CI tho with that same error - [here is the line](https://github.com/nicolasblanco/rails_param/runs/2891043140?check_suite_focus=true#step:4:12).

I don't mind looking further into this, but not really sure where to go at this point. Any thoughts on this?

**Comment by iMacTia** [comment]
You know what, I don't use Rubinius, if you also don't use it then we should probably just drop it for v1.0
Happy to restore it in case a maintainer comes forward that would like to help us, because otherwise this is just going to bite us back again and again
